### ISSUE TITLE
yappcap doesn't stop the loop

### ISSUE THREAD

**Issue by fvmt** [otherwiseguy/yappcap#1]
The following code doesn't stop by timeout or after receiving 100 packets. It stops only after ctrl+Z or segmentation fault:

from yappcap import *
p = PcapLive("eth1", autosave='test1.pcap')
p.timeout=1
p.activate()
p.filter = 'port 25'
p.loop(100, None)

Could it be libpcap? I've also tried pypcap and it didn't react on ctrl+c either. I've managed to make it record packets to file, but it also failed to stop by timeout or by exceeding number of packets. What could be the problem? Is there some diagnostic information that may be useful to solve the problem?

**Comment by otherwiseguy** [comment]
Actually, according to the pcap_loop man page:

> pcap_loop() processes packets from a live capture or ``savefile'' until cnt packets are processed, the end of the ``savefile'' is reached when reading from a ``savefile'', pcap_breakloop() is called, or an error occurs.  **It does not return when live read timeouts occur**.   A value of -1 or 0 for cnt is equivalent to infinity, so that packets are processed until another ending condition occurs.

Documenting and closing.
